In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')
test_dataset2 = test_dataset

In [3]:
train_dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
test_dataset

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [5]:
def clean(data):
    data = data.drop(['Cabin','Ticket', 'Name', 'PassengerId'],axis=1)
    data['Age'] =  data['Age'].fillna(data['Age'].median())
    data['Embarked']=data['Embarked'].fillna("S")     
    data['Fare'] = data['Fare'].fillna(data['Fare'].median())
    return data

In [6]:
train_dataset = clean(train_dataset)
train_dataset

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
test_dataset = clean(test_dataset)
test_dataset

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male  27.0      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male  27.0      0      0    8.0500        S
417       3    male  27.0      1      1   22.3583        C

[418 rows x 7 columns]

In [8]:
test = test_dataset.values

In [9]:
X = train_dataset.iloc[:, 1:].values
y = train_dataset.iloc[:, 0].values 

In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

le_test = LabelEncoder()
le_train = LabelEncoder()
test[:, 1] = le_test.fit_transform(test[:, 1])
X[:, 1] = le_train.fit_transform(X[:, 1])

ct_test = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[-1])], remainder='passthrough')
ct_train = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[-1])], remainder='passthrough')
test = ct_test.fit_transform(test)
X = ct_train.fit_transform(X)

In [11]:
test

array([[0.0, 1.0, 0.0, ..., 0, 0, 7.8292],
       [0.0, 0.0, 1.0, ..., 1, 0, 7.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 9.6875],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 7.25],
       [0.0, 0.0, 1.0, ..., 0, 0, 8.05],
       [1.0, 0.0, 0.0, ..., 1, 1, 22.3583]], dtype=object)

In [12]:
X

array([[0.0, 0.0, 1.0, ..., 1, 0, 7.25],
       [1.0, 0.0, 0.0, ..., 1, 0, 71.2833],
       [0.0, 0.0, 1.0, ..., 0, 0, 7.925],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 2, 23.45],
       [1.0, 0.0, 0.0, ..., 0, 0, 30.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 7.75]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=420)

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
classifier = SVC(kernel='linear', C=1).fit(X_train, y_train)
y_pred = classifier.predict(X_test)
score = classifier.score(X_test, y_test)
cm = confusion_matrix(y_test, y_pred)
print(f"{cm}, Score {score}")

[[95 10]
 [20 54]], Score 0.8324022346368715


In [16]:
y_prediction = classifier.predict(test)
submission = pd.DataFrame({
    "PassengerId" : test_dataset2["PassengerId"],
    "Survived" : y_prediction
})
submission.head(50)

PassengerId  Survived
0           892         0
1           893         1
2           894         0
3           895         0
4           896         1
5           897         0
6           898         1
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1
15          907         1
16          908         0
17          909         0
18          910         1
19          911         1
20          912         0
21          913         0
22          914         1
23          915         0
24          916         1
25          917         0
26          918         1
27          919         0
28          920         0
29          921         0
30          922         0
31          923         0
32          924         1
33          925         1
34          926         0
35          927         0
36          928         1
37          929         1
38          930         0
39          931         0
40          932         0
41          933         0
42          934         0
43          935         1
44          936         1
45          937         0
46          938         0
47          939         0
48          940         1
49          941         1