In [2]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [6]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [34]:
ann = tf.keras.models.Sequential() # Initializing ANN 

In [35]:
# Adding the input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [36]:
# Adding the second hidden layer 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [37]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # if not binary classification we use activation 'softmax'

In [38]:
# TRAINING ANN 
# Compiling ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) # if not binary classification we use loss = 'categorical_crossentropy'

In [39]:
# Training ANN on the Training Set
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6610 - accuracy: 0.5859
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4879 - accuracy: 0.7895
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4499 - accuracy: 0.7984
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4347 - accuracy: 0.8010
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.8043
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4205 - accuracy: 0.8121
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4156 - accuracy: 0.8161
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4102 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4042 - accuracy: 0.8223
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3974 - accura

In [47]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

In [46]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.07858154]], dtype=float32)

In [49]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print(cm); print(ac)

[[1584   11]
 [ 336   69]]
0.8265
