In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [6]:
ann = tf.keras.models.Sequential() # Initializing ANN 

In [7]:
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

In [8]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))

In [9]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) 

In [10]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) 

In [11]:
ann.fit(x_train, y_train, batch_size=20, epochs=200)

Epoch 1/200
400/400 [==============================] - 1s 1ms/step - loss: 0.4432 - accuracy: 0.8051
Epoch 2/200
400/400 [==============================] - 0s 1ms/step - loss: 0.3642 - accuracy: 0.8531
Epoch 3/200
400/400 [==============================] - 0s 1ms/step - loss: 0.3474 - accuracy: 0.8576
Epoch 4/200
400/400 [==============================] - 0s 1ms/step - loss: 0.3416 - accuracy: 0.8594
Epoch 5/200
400/400 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 0.8624
Epoch 6/200
400/400 [==============================] - 1s 1ms/step - loss: 0.3331 - accuracy: 0.8631
Epoch 7/200
400/400 [==============================] - 1s 2ms/step - loss: 0.3303 - accuracy: 0.8648
Epoch 8/200
400/400 [==============================] - 1s 2ms/step - loss: 0.3277 - accuracy: 0.8664
Epoch 9/200
400/400 [==============================] - 1s 2ms/step - loss: 0.3249 - accuracy: 0.8643
Epoch 10/200
400/400 [==============================] - 1s 2ms/step - loss: 0.3243 - accura

400/400 [==============================] - 1s 2ms/step - loss: 0.2412 - accuracy: 0.8989
Epoch 82/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2393 - accuracy: 0.8974
Epoch 83/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2400 - accuracy: 0.8986
Epoch 84/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2376 - accuracy: 0.8976
Epoch 85/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2352 - accuracy: 0.8990
Epoch 86/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2346 - accuracy: 0.9005
Epoch 87/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2342 - accuracy: 0.9005
Epoch 88/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2341 - accuracy: 0.9018
Epoch 89/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2338 - accuracy: 0.9036
Epoch 90/200
400/400 [==============================] - 1s 2ms/step - loss: 0.2326 - accuracy: 

400/400 [==============================] - 1s 2ms/step - loss: 0.1873 - accuracy: 0.9172
Epoch 161/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1874 - accuracy: 0.9214
Epoch 162/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1856 - accuracy: 0.9206
Epoch 163/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1878 - accuracy: 0.9196
Epoch 164/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1840 - accuracy: 0.9235
Epoch 165/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1832 - accuracy: 0.9215
Epoch 166/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1845 - accuracy: 0.9186
Epoch 167/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1827 - accuracy: 0.9235
Epoch 168/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1815 - accuracy: 0.9225
Epoch 169/200
400/400 [==============================] - 1s 2ms/step - loss: 0.1819 - a

In [12]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

In [13]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.01032799]], dtype=float32)

In [14]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print(cm); print(ac)

[[1448  147]
 [ 198  207]]
0.8275
